### ISSUE TITLE
DateTimeStamp compareTo function is not transitive

### ISSUE THREAD

**Issue by dsgrieve** [microsoft/gctoolkit#77]
As exhibited by pull request #76

**Comment by anantk24** [comment]
- Does that mean  `Datetimestamp` constructor should calculate timestamp value if  `ZonedDateTime` is passed ? 
- Current comparision if any 'ZonedDateTime' is null it will compare timestamp value otherwise first compare dateTime then compare timestamp.
- Currently `new DateTimeStamp("2021-09-01T11:12:13.111-0100", 100)` will have timestamp value as 100

**Comment by kabutz** [comment]
Yeah, that's why I didn't suggest a fix - I think @kirk-microsoft needs to decide in which order he wants these events to be sorted.
